### PR TITLE
[WIP] Small changes to help backend-frontend communication.

### PR DESCRIPTION
**Pull request by notoraptor**
Hi @DatCorno @Vahe987 @vict0rsch , in order to make web interface work correctly with the backend, I had to add these small changes:

- Return more 404 errors when an address cannot be found by Google.
- Let server handle Cross Origin Resource Sharing (CORS) to allow API calls from a client to a server at different origin.

### CODE REVIEW

**Comment by notoraptor** [comment]
PS: I realize that I may need to add supplementary code and make other small changes to help front-end. So, I suggest that @DatCorno does not merge this branch as long as my code is not stable.

Anyway, all my code suggestions about backend will be listed here.

**Comment by marpaia** [comment]
Hey @notoraptor, I was looking through your changes here and I added the CORS wrapper here: https://github.com/cc-ai/floods-backend/commit/5ababa7899ff22e8be85e96c7ec03392b67b4d3a. Perhaps we can chat on Slack about the other changes you need and I can port them over for you.

**Comment by marpaia** [comment]
For the time being, I deployed the API at http://api.climate-change-ai.com (for example, try [this link](http://api.climate-change-ai.com/address/version/6666%20St%20Urbain%20St%2C%20Montreal%2C%20QC%20H2S%203H1%2C%20Canada)).

**Comment by notoraptor** [comment]
Hi here ! I have updated frontend to correctly match current backend on which @marpaia works. Everything seems OK for now. If I need anything else, I will inform you !

FYI, this PR also added a new endpoint to call Google autocompletion API from backend because I had some issues calling it directly from Javascript. But now it works fine and I can make many Google API calls directly from front-end.

So, I close this PR as it is not needed anymore.

**Pull request closed without merging**
